### ISSUE TITLE
How can set the message head data?

### ISSUE THREAD

**Issue by cfanboy** [tinode/dart-sdk#9]
I want to send a Drafty type message, such as Image via SDK,  but cannot find where to set it

**Comment by rxmoein** [comment]
Hello,
This is not possible right now. If you need to send an image you can define a custom data structure that contains the image base64 data or url and parse your structure when reading the message.
The message content is not supposed to be only string and it's `dynamic`. So you can pass serialized json or a `Map` as your message content.

**Comment by cfanboy** [comment]
got it, thanks a lot.
